# Continuous integration for Windows using http://appveyor.com/

# Not a .NET project, we build ci-helpers in the install step instead
build: false

# Only build pushes to the master branch. Will still build tags and pull requests.
branches:
    only:
        - master

environment:
    matrix:
        - MINICONDA: C:\Miniconda35-x64
          PYTHON: 3.5
        - MINICONDA: C:\Miniconda36-x64
          PYTHON: 3.6
        - MINICONDA: C:\Miniconda37-x64
          PYTHON: 3.7

init:
    # Add miniconda to the PATH
    - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"
    # The file with the listed requirements to be installed by setup-miniconda.bat
    - set CONDA_REQUIREMENTS=requirements.txt
    - set CONDA_REQUIREMENTS_DEV=requirements-dev.txt
    # Cartopy, scipy, and proj aren't on conda-forge for some reason.
    - set CONDA_EXTRA_CHANNEL=defaults

install:
    # Copy sample data to the verde data dir to avoid downloading all the time
    - ps: mkdir -p ~\.verde\data\master
    - ps: cp data\* ~\.verde\data\master
    # Get the Fatiando CI scripts
    - cmd: git clone https://github.com/fatiando/continuous-integration.git
    # Setup miniconda and install the requirements into a new environment
    - cmd: continuous-integration\appveyor\setup-miniconda.bat
    # Activate the new environment
    - cmd: activate testing
    # Show installed pkg information for postmortem diagnostic
    - cmd: conda list
    # Make a source package for the project and install it
    - cmd: python setup.py sdist --formats=zip
    - ps: ls dist
    - ps: pip install --no-deps (Get-ChildItem dist\*.zip)


test_script:
    # Run the tests inside a tmp folder to make sure we're testing the installed version
    - ps: mkdir -p tmp; cd tmp; python -c "import verde; verde.test()"
