name: verde
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.12
    - pip
    # Build
    - twine
    - build
    # Run
    - numpy
    - scipy
    - pandas
    - xarray
    - scikit-learn
    - pooch
    - dask>=2022.01.0
    # Optional
    - pykdtree
    - numba
    # Test
    - matplotlib==3.8.*
    - cartopy>=0.20
    - pytest
    - pytest-cov
    - pytest-mpl
    - coverage
    # Documentation
    - sphinx==7.2.*
    - sphinx-book-theme==1.1.*
    - sphinx-gallery==0.15.*
    - sphinx-copybutton==0.5.*
    - sphinx-design==0.5.*
    - jupyter-sphinx==0.5.*
    - pyproj
    - pygmt==0.11.*
    - gmt==6.5.*
    - ipython
    - ensaio
    # Style
    - black
    - pathspec
    - isort
    - flake8
    - flake8-bugbear
    - flake8-builtins
    - flake8-functions
    - flake8-mutable
    - flake8-rst-docstrings
    - flake8-simplify
    - flake8-unused-arguments
    - pep8-naming
    - pip:
        - burocrata
