name: verde
channels:
    - conda-forge
    - defaults
dependencies:
    - python==3.11
    - pip
    # Build
    - twine
    - build
    # Run
    - numpy
    - scipy
    - pandas
    - xarray
    - scikit-learn
    - pooch
    - dask!=2021.03.0
    # Optional
    - pykdtree
    - numba
    # Test
    - matplotlib==3.5.*
    - cartopy>=0.20
    - pytest
    - pytest-cov
    - pytest-mpl
    - coverage
    # Documentation
    - sphinx==4.5.*
    - sphinx-book-theme==0.3.*
    - sphinx-gallery==0.10.*
    - sphinx-copybutton==0.5.*
    - sphinx-design==0.1.*
    - pyproj
    - pygmt==0.6.*
    - gmt==6.3.*
    - ipython
    # Style
    - black
    - pathspec
    - isort
    - flake8
    - flake8-bugbear
    - flake8-builtins
    - flake8-functions
    - flake8-mutable
    - flake8-rst-docstrings
    - flake8-simplify
    - pep8-naming
    - pip:
        # Install flake8-unused-arguments through pip
        # (not available through conda yet)
        - flake8-unused-arguments
