name: verde
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - pip
    - numpy
    - scipy
    - pandas
    - xarray
    - scikit-learn
    - pooch
    - dask
    # Optional
    - pykdtree
    - numba
    # Development requirements
    - pyproj
    - matplotlib
    - cartopy==0.17.*
    - pytest
    - pytest-cov
    - pytest-mpl
    - coverage
    - black>=20.8b1
    - pylint=2.4.*
    - flake8
    - sphinx=2.2.1
    - sphinx_rtd_theme=0.4.3
    - sphinx-gallery
    - numpydoc
